# Generated by Django 4.0.4 on 2022-04-26 21:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='model_SmallTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('priority', models.IntegerField(default=0)),
                ('description', models.CharField(default='', max_length=512)),
                ('complete', models.BooleanField(default=False)),
                ('assigned_user', models.UUIDField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='model_User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=32)),
                ('present', models.BooleanField(default=True)),
                ('entry_year', models.DateField()),
                ('pin_hash', models.CharField(default='', max_length=256)),
            ],
        ),
    ]
